[project]
name = "stt"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "fastapi[standard]",
  "pydub",
  "speechrecognition",
  "ruff",
  "python-multipart>=0.0.20",
]
